# Generated by Django 4.1 on 2022-08-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento_nombre', models.CharField(max_length=50)),
                ('elemento_simbolo', models.CharField(max_length=50)),
                ('numero_atomico', models.CharField(max_length=50)),
                ('elemento_grupo', models.CharField(max_length=50)),
            ],
        ),
    ]
